kind: Deployment
apiVersion: apps/v1
metadata:
  name: flower-fundraiser-processing
  labels:
    app: flower-fundraiser-processing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flower-fundraiser-processing
  template:
    metadata:
      name: flower-fundraiser-processing
      labels:
        app: flower-fundraiser-processing
    spec:
      containers:
        - name: flower-fundraiser-processing
          image: 'melvis02/flower-fundraiser-processing:latest'
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
kind: Service
apiVersion: v1
metadata:
  name: flower-fundraiser-processing
spec:
  selector:
    app: flower-fundraiser-processing
  ports:
    - name: flower-fundraiser-processing-port
      port: 443
      protocol: TCP
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flower-fundraiser-processing
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  spec:
    rules:
    - host: flowers.treympick.me
      http:
        paths:
        - backend:
            service:
              name: flower-fundraiser-processing
              port:
                number: 443
          path: /(.*)
          pathType: ImplementationSpecific
    tls:
    - hosts:
      - flowers.treympick.me
---

